### ISSUE TITLE
How do you use 2Do?

### ISSUE THREAD

**Issue by lardissone** [nikivdev/flow#16]
I see you have a lot of projects in black and one in red, then grouped by DUE and WORKING.

Can you please explain how do you organize your 2Do tasks?

**Comment by jchristgit** [comment]
There's some information on [this Medium post](https://medium.com/@NikitaVoloboev/project-based-learning-e511641869ca), but that does not really explain too much. I'd also be interested in this though - I have 2Do, but I don't really have a good organization scheme.

**Comment by lardissone** [comment]
@Volcyy yes, I've seen that, but he explains more how to integrate to the time tracking + hammerspoon than 2Do itself.

I tend to not use 2Do much because now I'm pretty dirty organized and it's being worse than just remind things myself. And finally I end using Inbox + Today sections only.

**Comment by nikivdev** [comment]
I was actually thinking of writing a dedicated article on how I use 2Do because for me the selling point of the app is just how flexible you can really be with it.

I updated the repository though and added an unblurred screenshot of my sidebar : 

![](http://i.imgur.com/ZR47YoR.png) 

You can navigate to the group you need by pressing J key. I use that very often. You can move tasks around with M key. And you can search tasks within a list with F key. I have a rather complicated setup though with 2Do since I add time estimates to each task, like here : 

![2017-08-28 at 18 07](https://user-images.githubusercontent.com/6391776/29782174-db41370c-8c1b-11e7-9160-1d5832455769.png)

It's better I write an article on it though, I've been meaning to do it for some time. 🙂

**Comment by nikivdev** [comment]
I am writing about my workflow with 2Do in [my wiki](https://nikitavoloboev.gitbooks.io/knowledge/content/macOS/apps/2Do.html) :)
