### ISSUE TITLE
Desktop Wallpaper?

### ISSUE THREAD

**Issue by Axel-Jacobsen** [nikivdev/flow#36]
Would you be able to share the desktop wallpaper?

EDIT: And in general more of your Iterm mods. You have ScreenFetch and the external colour sheet, but how do you make it look so clean? i.e. remove top bar, remove most of the text prompts

Thanks!

**Comment by nikivdev** [comment]
Found wallpaper on Unsplash but can't find it now. [Here](https://transfer.sh/i8Xfj/photo-1462903004115-f8e27d6a3985.jpeg) is the download of it.

As for iTerm, borderless can be activated in the settings. I switched to [pure](https://github.com/sindresorhus/pure) theme since the screenshot was taken and recommend it.

**Comment by Axel-Jacobsen** [comment]
Thanks!
